#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# export TACHIDESK_DBPATH=/config

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 8085" \
    cd /app/tachidesk s6-setuidgid abc java -Dsuwayomi.tachidesk.config.server.rootDir="/config" -jar /app/tachidesk/Tachidesk-Server-Latest.jar \
    -nobrowser -data=/config
