name: Issue moderator

on:
  issues:
    types: [opened, edited, reopened]
  issue_comment:
    types: [created]

jobs:
  autoclose:
    runs-on: ubuntu-latest
    steps:
      - name: Moderate issues
        uses: tachiyomiorg/issue-moderator-action@v1
        with:
          repo-token: ${{ github.token }}
          duplicate-check-enabled: true
          duplicate-check-label: Source request
          existing-check-enabled: true
          existing-check-label: Source request
          auto-close-rules: |
            [
              {
                "type": "title",
                "regex": ".*<short description>.*",
                "message": "You did not fill out the description in the title"
              },
              {
                "type": "title",
                "regex": ".*(<|>)+.*",
                "message": "You did not remove Angle brackets(< and >) from the title"
              },
              {
                "type": "body",
                "regex": ".*DELETE THIS SECTION IF YOU HAVE READ AND ACKNOWLEDGED IT.*",
                "message": "The acknowledgment section was not removed"
              },
              {
                "type": "body",
                "regex": ".*(Suwayomi-Server version|Server Operating System|Server Desktop Environment|Server JVM version|Client Operating System|Client Web Browser):.*(\\(Example:|<usually).*",
                "message": "The requested information was not filled out"
              },
              {
                "type": "body",
                "regex": ".*Remove this line after you are done.*",
                "message": "The lines requesting to be removed were not removed."
              }
            ]
