name: CI Publish

on:
  workflow_dispatch:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_wrapper:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v6

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v5

  build:
    name: Build Jar
    needs: check_wrapper
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}
          path: master
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Copy CI gradle.properties
        run: |
          cd master
          mkdir -p ~/.gradle
          cp .github/runner-files/ci-gradle.properties \
            ~/.gradle/gradle.properties

      - name: Build and copy webUI, Build Jar
        env:
          ProductBuildType: "Stable"
        working-directory: master
        run: ./gradlew :server:downloadWebUI :server:shadowJar --stacktrace

      - name: Upload Jar
        uses: actions/upload-artifact@v7
        with:
          name: jar
          path: master/server/build/*.jar
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: jar
          path: release

      - name: Generate checksums
        run: cd release && sha256sum * > Checksums.sha256

      - name: Get tag from Jar
        run: |
          for file in $(find ./release -name "*.jar"); do
            filename=$(basename "$file" .jar)
            part3=$(echo "$filename" | cut -d'-' -f3)
            echo "TAG=$part3" >> $GITHUB_ENV
          done
        shell: bash

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          token: ${{ secrets.BUILD_PREVIEW_TOKEN }}
          files: release/*
          prerelease: false
          draft: false
          tag_name: ${{ env.TAG }}
